FROM python:3.11.4

WORKDIR /app

RUN apt-get update && \
    apt-get install -y poppler-utils && \
    apt-get clean

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN 
RUN pip install -r requirements.txt

WORKDIR /app/src

CMD ["sh", "-c", "python main.py > /app/logs/app.log 2>&1 & tail -f /app/logs/app.log"]

# logging 上書き
# CMD ["sh", "-c", "python main.py >> /app/logs/app.log 2>&1 & tail -f /app/logs/app.log"]